[2025-03-23T19:09:38.609+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T19:09:38.620+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schedule.run_copy_clientes manual__2025-03-23T19:09:37.420384+00:00 [queued]>
[2025-03-23T19:09:38.625+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schedule.run_copy_clientes manual__2025-03-23T19:09:37.420384+00:00 [queued]>
[2025-03-23T19:09:38.625+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-23T19:09:38.632+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_copy_clientes> on 2025-03-23 19:09:37.420384+00:00
[2025-03-23T19:09:38.636+0000] {standard_task_runner.py:72} INFO - Started process 2334 to run task
[2025-03-23T19:09:38.640+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'schedule', 'run_copy_clientes', 'manual__2025-03-23T19:09:37.420384+00:00', '--job-id', '1915', '--raw', '--subdir', 'DAGS_FOLDER/dag_master.py', '--cfg-path', '/tmp/tmpr_wpdtsy']
[2025-03-23T19:09:38.642+0000] {standard_task_runner.py:105} INFO - Job 1915: Subtask run_copy_clientes
[2025-03-23T19:09:38.662+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-23T19:09:38.697+0000] {task_command.py:467} INFO - Running <TaskInstance: schedule.run_copy_clientes manual__2025-03-23T19:09:37.420384+00:00 [running]> on host b612e1a2c49c
[2025-03-23T19:09:38.759+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='schedule' AIRFLOW_CTX_TASK_ID='run_copy_clientes' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T19:09:37.420384+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T19:09:37.420384+00:00'
[2025-03-23T19:09:38.760+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T19:09:38.767+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-23T19:09:38.768+0000] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'docker exec linux_python /bin/bash -c \'/workspace/scripts/run_copy.sh /var/lib/postgresql/exports/clientes.csv /path/to/move_cloud/clientes && echo "Script Executado com Sucesso!"\'']
[2025-03-23T19:09:38.775+0000] {subprocess.py:99} INFO - Output:
[2025-03-23T19:09:38.944+0000] {subprocess.py:106} INFO - -----------------------------------------------------------------------
[2025-03-23T19:09:38.947+0000] {subprocess.py:106} INFO - ------------------------- START SCRIPT --------------------------------
[2025-03-23T19:09:38.947+0000] {subprocess.py:106} INFO - -----------------------------------------------------------------------
[2025-03-23T19:09:38.948+0000] {subprocess.py:106} INFO - Arquivo /var/lib/postgresql/exports/clientes.csv encontrado!
[2025-03-23T19:09:38.968+0000] {subprocess.py:106} INFO - INFO:root:Copia /var/lib/postgresql/exports/clientes.csv para /path/to/move_cloud/clientes/clientes.csv
[2025-03-23T19:09:38.973+0000] {subprocess.py:106} INFO - INFO:root:/var/lib/postgresql/exports/clientes.csv copiado com sucesso.
[2025-03-23T19:09:38.974+0000] {subprocess.py:106} INFO - INFO:root:### A primeira linha de clientes.csv Ã©: ['client_id', 'nome', 'sobrenome', 'cpf', 'rg', 'data_nascimento', 'est_civil', 'genero', 'email', 'tel_res', 'tel_cel', 'endereco', 'pais', 'cidade', 'estado', 'cep', 'nacionalidade', 'renda', 'cargo', 'tp_cliente', 'data_criacao']
[2025-03-23T19:09:38.984+0000] {subprocess.py:106} INFO - Script Executado com Sucesso!
[2025-03-23T19:09:38.993+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-23T19:09:39.033+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T19:09:39.034+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=schedule, task_id=run_copy_clientes, run_id=manual__2025-03-23T19:09:37.420384+00:00, execution_date=20250323T190937, start_date=20250323T190938, end_date=20250323T190939
[2025-03-23T19:09:39.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T19:09:39.162+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-23T19:09:39.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
